### ISSUE TITLE
Hoverboard hack IDE

### ISSUE THREAD

**Issue by Tirta01** [LeoDJ/Hoverboard-Board-Hack#1]
Hi, I am interested in your project about Hoverboard hack. Before, i tried to make [openchair project](https://hackaday.io/project/13347-openchair) from hackaday.io, it uses Nucleo F446RE to control mainboard, but I cant get it to work with some warning messages when flashing the firmware. my question

1. What is the IDE program to flash firmware to mainboard?
2. How to make original firmware backups of the mainboard, before uploading a new one. Any other limitations for considering?
3. The chip on mainboard of my hoverboard is GD32F103RCT6, any issue about incompatablility?

It helps me a lot with decision how to proceed further. Many thanks for your reply and help.

**Comment by LeoDJ** [comment]
1. I don't use any particular IDE. I am using the Makefile and Linux. I just had to install the armhf binaries and change the path in the Makefile. So I cd into the directory and run `make`. Then I upload the .bin file using the ST-Link utility.
2. Sadly it is not possible to dump the official firmware because of the read protection and I didn't find it on the internet either. So you have to be sure you don't want to use the official firmware anymore, or you have more luck than me in finding it online.
3. No, this is still the same chip that is used on all hoverboard mainboards (F103RCT6). It should work fine.

**Comment by Tirta01** [comment]
Hi, many thanks for your reply.. I run windows 7 x64 installation,. Anyhow, thanks again! and happy Christmas to you :), Best regards, Tirta.
